## Numpy tutorials

* its a general- purpose array processing package
* It is a scientific computing library for python
* Support large no. of data in the form of multi-dimentional array and matrix
* Use for mathematical calculation like linear algebra , fourier transform etc.

### What is array ?

An array is a data structure that stores some value of same data type . In python, this is the main difference between lists and arrays. while python list can contain values corresponding to different data types , arrays in python can only contain values corresponding to same data type

In [2]:
import numpy as np

In [3]:
arr_1 = np.array([1,2,3,4,5,6])
arr_1

array([1, 2, 3, 4, 5, 6])

In [4]:
type(arr_1)

numpy.ndarray

In [5]:
print(arr_1.ndim)

1


In [6]:
arr2 = np.array([[1,2.0,3],[5,6,7]])
arr2

array([[1., 2., 3.],
       [5., 6., 7.]])

In [7]:
print(arr2.size)
print(arr2.ndim)
print(arr2.shape)
print(arr2.dtype)

6
2
(2, 3)
float64


In [8]:
ones = np.ones(4)
print(ones)

[1. 1. 1. 1.]


In [9]:
ones = np.ones((3,4),dtype = int)
print(ones)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [10]:
zeros = np.zeros((3,4,5))
print(zeros)
print(zeros.ndim)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]
3


## Arange()

In [11]:
# np.arange(start , end , steps)
b = np.arange(1,5)
print(b)
type(b)

[1 2 3 4]


numpy.ndarray

In [12]:
odd = np.arange(1,13,2)
print(odd)

[ 1  3  5  7  9 11]


In [13]:
arr_1d = np.arange(1,13)
print(arr_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


## linspace()

In [15]:
np.linspace(1,6,4) # it will create equal space between numbers

array([1.        , 2.66666667, 4.33333333, 6.        ])

## Reshape()

In [16]:
arr_2 = arr_1d.reshape(2,6) 
arr_2

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [17]:
arr_3 = arr_1d.reshape(2,2,3)
print(arr_3)
print(arr_3.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3


# ravel()

In [18]:
arr_3.ravel() # it will create multi-dimentional array into 1 D array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## flatten()

In [19]:
arr_2.flatten() # it will create multi-dimentional array into 1 D array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## transpose()

In [20]:
arr_2.transpose()

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

In [22]:
arr_2.shape

(2, 6)

In [23]:
arr1 = np.arange(1,13).reshape(3,4)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [24]:
arr2 = np.arange(1,13).reshape(3,4)
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
arr1+arr2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [26]:
arr1/arr2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
arr1 *arr2

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [28]:
np.multiply(arr1,arr2)

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [29]:
arr1 @ arr2.transpose()

array([[ 30,  70, 110],
       [ 70, 174, 278],
       [110, 278, 446]])

In [30]:
arr1.dot(arr2.transpose())

array([[ 30,  70, 110],
       [ 70, 174, 278],
       [110, 278, 446]])

In [31]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [32]:
arr1.max(axis = 0) # max of columns

array([ 9, 10, 11, 12])

In [33]:
arr1.max(axis = 1) # max of rows

array([ 4,  8, 12])

In [34]:
np.sum(arr1)

78

In [35]:
np.sum(arr1 , axis = 0)

array([15, 18, 21, 24])

In [36]:
np.mean(arr1)

6.5

In [37]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162]])

In [38]:
np.std(arr1)

3.452052529534663

In [39]:
np.exp(arr1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05]])

In [40]:
np.log(arr1)

array([[0.        , 0.69314718, 1.09861229, 1.38629436],
       [1.60943791, 1.79175947, 1.94591015, 2.07944154],
       [2.19722458, 2.30258509, 2.39789527, 2.48490665]])

In [41]:
np.log10(arr1)

array([[0.        , 0.30103   , 0.47712125, 0.60205999],
       [0.69897   , 0.77815125, 0.84509804, 0.90308999],
       [0.95424251, 1.        , 1.04139269, 1.07918125]])

In [42]:
mx = np.arange(1,101).reshape(10,10)
mx

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [43]:
mx[4,3] # rows * column

44

In [44]:
mx[4,3].ndim

0

In [45]:
mx [:,0]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [46]:
mx [:,0:3]

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33],
       [41, 42, 43],
       [51, 52, 53],
       [61, 62, 63],
       [71, 72, 73],
       [81, 82, 83],
       [91, 92, 93]])

In [47]:
mx [1:4,3:6]

array([[14, 15, 16],
       [24, 25, 26],
       [34, 35, 36]])

In [48]:
matrix1 = np.arange(1,17).reshape(4,4)
print(matrix1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [49]:
matrix2 = np.arange(17, 33).reshape(4,4)
print(matrix2)

[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [50]:
np.concatenate((matrix1,matrix2), axis = 0) # it will concatenate by column wise

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [51]:
np.concatenate((matrix1,matrix2), axis = 1) # it will concatenate by row wise

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [52]:
np.hstack((matrix1,matrix2))

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [53]:
np.vstack((matrix1,matrix2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [54]:
np.sin(np.pi/2)

1.0

In [55]:
np.cos(0)

1.0

In [56]:
np.tan(180)

1.3386902103511544

In [57]:
np.tan(np.pi/2)

1.633123935319537e+16

## Random sampling with numpy

In [58]:
import random

In [60]:
np.random.random(1) 

array([0.12368653])

In [61]:
np.random.random([3,3])

array([[0.09919561, 0.63300539, 0.49406027],
       [0.9450188 , 0.82004233, 0.85688475],
       [0.89171001, 0.63816281, 0.92587673]])

In [64]:
np.random.randint(1,5,(3,3))

array([[3, 1, 1],
       [4, 2, 3],
       [4, 4, 1]])

In [67]:
np.random.seed(11) # 2^32 -1
np.random.randint(1,5,(3,3))

array([[2, 4, 1],
       [4, 2, 4],
       [2, 1, 2]])

In [69]:
a = [1,2,3,4,5,6,7,8]
for i in range(10):
    print(np.random.choice(a))

6
5
3
5
2
3
6
6
8
5


## String operation

In [71]:
first_name = "Prem "
last_name = " Bharti"

In [72]:
np.char.add(first_name , last_name)

array('Prem  Bharti', dtype='<U12')

In [73]:
np.char.upper(first_name)

array('PREM ', dtype='<U5')